apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway  # <-- Corrected selector label
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: zakaria469980/apigateway:latest
        ports:
        - containerPort: 8080
  
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-srv
spec:
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 8080 # externl port
      targetPort: 80 # internal port
      name: http-port
    - protocol: TCP
      port: 8181 # externl port
      targetPort: 443 # internal port
      name: https-port
  # LoadBalancer to expose service externally, Should use nodePort or ClusterIp when Ingress is setup
  type: LoadBalancer
