# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Build and push Docker image
      run: |
        docker build -t zakaria469980/apigateway .
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push zakaria469980/apigateway:latest

    # - name: Install Azure CLI
    #   run: |
    #     curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

    # - name: AKS Login
    #   run: az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

    # - name: Set AKS Context
    #   run: az aks get-credentials --resource-group <FootTweetsCluster_group> --name <myakscluster>

    # - name: Deploy to AKS
    #   run: kubectl apply -f deployment.yaml